= Favorite Coffee -- Coffee recommendation with Neo4j and Quarkus

How to build a coffee beans recommendation with Neo4j and Quarkus.


== Development

Requires Docker, Maven, JDK 16 (eg via sdkman).


You can start a fresh Neo4j instance with:

[source,bash]
----
./run-graph-db.sh
----

In another terminal, run the following to create the sample data:

[source,bash]
----
docker exec `docker ps -qf name=graph-db` /var/lib/neo4j/bin/cypher-shell -u neo4j -p test --file /import/load-coffee-data.cypher
----

Or alternatively run the Cypher-Queries in your IDE or the http://localhost:7474/browser/[Neo4j Browser^].


Then run the application in development mode (connecting to the local Neo4j server) with:

[source,bash]
----
mvn quarkus:dev
----

Then, explore the coffee website at: http://localhost:8080/

== Production

You can create your online free cloud instance of Neo4j at https://dev.neo4j.com/aura

After creating your database copy your connection URL and password into `application.properties`:

----
# Your Neo4J Aura URI, use `neo4j` instead of `neo4j+s`, due to a Quarkus issue in 2.1.2
quarkus.neo4j.uri=neo4j://xxxxab01.databases.neo4j.io
quarkus.neo4j.encrypted=true
quarkus.neo4j.authentication.username=[...]
quarkus.neo4j.authentication.password=[...]
----

Then you ou can package your application and run the jar (prod mode).

[source,bash]
----
mvn package
java -jar target/favorite-coffee-runner.jar
----

// == How does it work

// See these blog posts at:
